version: "3"

services:

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      graphingcalc_network:
        aliases:
          - redis

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      graphingcalc_network:
        aliases:
          - rabbitmq

  web: &web
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./calcs:/app
    command: flask run --debugger --host=0.0.0.0
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    depends_on:
      - redis
      - rabbitmq
      - celery-worker
      - SQLdb
    networks:
      graphingcalc_network:
        aliases:
          - web

  celery-worker:
    <<: *web
    ports: []
    scale: 0
    command: celery -A main.celery worker -l info
    depends_on:
      - redis
      - rabbitmq
    networks:
      graphingcalc_network:
        aliases:
          - celery-worker

  SQLdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: graphingcalc
    networks:
      graphingcalc_network:
        aliases:
          - postgres

networks:
  graphingcalc_network:

